### ISSUE TITLE
Hacer que las imágenes de algunas grilas ocupen el 100% del item y otras no

### ISSUE THREAD

**Issue by agustinlopini** [hernan224/marmoleria_alba#21]
Las grillas de, por ejemplo, mármoles o granitos deben ocupar el 100% del item cuadrado (background: cover, tal vez?) y las de broncería, por ejemplo bachas, que se mantengan a la proporción como están ahora.

Tal vez agregando una clase especial a esas grillas se puede hacer no?

**Comment by hernan224** [comment]
Pasa que esta todo generado con un solo template. Decime bien cuales grillas tienen que ir al 100% y cuales no, y veo si puedo meter algun condicional que cambie una clase, o algo por el estilo. Pero no se si se va a poder hacer sin tener qu generar un tamplate nuevo, y ahi se empeiza a complicar todo.

**Comment by hernan224** [comment]
LISTO, Falta elegir cuales son los items que tiene que ir en uno u otro modo. Incluso, de ser necesario, se puede llegar mejorar el armado de los thumb dependiendo de qué elemento sea.
