### ISSUE TITLE
Generar listado de catálogo a partir de las nuevas imágenes de Onemar

### ISSUE THREAD

**Issue by agustinlopini** [hernan224/marmoleria_alba#23]
Te encargo esta tarea porque la tenes más clara que yo. Las carpetas que hay que actualizar son:
marmoles, granitos nacionales, granitos importados y porfidos (esta ya la actualicé y le corregí que decía "porfidios", pero revisá de que estén los links bien a ese menú y a las imágenes)

**Comment by hernan224** [comment]
LISTO
